services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kenalbatik
  db:
    image: mysql:latest
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - kenalBatikVolume:/var/lib/mysql
    networks:
      - kenalbatik
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  kenalbatik:
    driver: bridge

volumes:
  kenalBatikVolume:
    driver: local
